name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    if: ${{ !cancelled() && ! failure() }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up PDM
        uses: pdm-project/setup-pdm@b2472ca4258a9ea3aee813980a0100a2261a42fc # v4.2
        with:
          cache: true
          python-version: ${{ matrix.python-version }}
          version: 2.22.4
          cache-dependency-path: |
            ./pdm.dev.lock
            ./pdm.lock
      - run: env | sort
      - run: make prerequisites
      - run: make dev
      - run: make lint test doc build
    strategy:
      matrix:
        os:
          # renovate: github-runner
          - macos-14
          # renovate: github-runner
          - ubuntu-24.04
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
